version: '3.4'

services:
    musify-db-env:
        build:
            context: .
            dockerfile: ./Dockerfile
        expose:
            - "5432"
        ports:
            - "0.0.0.0:5432:5432"
        environment:
            POSTGRES_PASSWORD: Musify_0903
        networks:
            musify_network: # Requiere ejecutarse docker network create --driver bridge --subnet 172.250.6.0/24 musify_network
                ipv4_address: 172.250.6.4

networks:
    musify_network:
        external: true
