name: Musify-db-env CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PG_PASS: ${{ secrets.PG_PASS }}

    steps:
    - uses: actions/checkout@v2

    - name: Build the docker-compose
      run: docker-compose build
    - name: Up the docker-compose as daemon
      run: docker-compose up -d
    - name: Check running containers
      run: docker ps -a
